shallow_clone: true

platform:
    - x64

environment:
    matrix:
        - PYTHON_DIR: C:\Python36
          MINICONDA_DIR: C:\Miniconda36-x64
          FREECAD_VERSION: 0.17

install:
    # Configure MiniConda
    - set PATH=%MINICONDA_DIR%;%MINICONDA_DIR%\Scripts;%PATH%
    - conda config --set always_yes yes
    - conda update --quiet conda

    # Install FreeCAD
    - conda install --quiet -c cadquery -c conda-forge freecad=%FREECAD_VERSION%
    - ps: >-
        $env:FREECAD_LIB = $env:MINICONDA_DIR + "\pkgs\" + $(
            $x = $(conda list -c freecad)
            $x = $x -Replace ".*::",""
            echo $x
        ) + "\lib"
    - echo FREECAD_LIB = %FREECAD_LIB%
    - conda list freecad

    # Configure Python & pip packages
    - set PATH=%PYTHON_DIR%;%PATH%
    - python --version
    - python -m pip install --upgrade pip
    - ps: >-
        Get-ChildItem "src/*/requirements.txt" |
        ForEach-Object {
            $c = ($_ | Get-Content)
            $c = $c -replace "^cqparts.*",""
            echo $c
        } | Sort | Get-Unique | ForEach-Object {
            if (-Not ([string]::IsNullOrEmpty($_))) {
                python -m pip install $_
            }
        }
    - python -m pip install -r tests/requirements.txt

build: false

test_script:
    - set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%\src
    - cd /d %APPVEYOR_BUILD_FOLDER%\tests
    - python runtests.py --ignore "catalogue"

on_success:
    - echo yay
